config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users
  root to: 'items#index'
  resources :items


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fish_fresh.rb
class FishFresh < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '抜群' },
    { id: 3, name: '良好' },
    { id: 4, name: '良' },
    { id: 5, name: '傷みあり' },
    { id: 6, name: '本日中' }

  ]

  include ActiveHash::Associations
  has_many :items


end

app/models/fish_recipe.rb
class FishRecipe < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'そのままの状態' },
    { id: 3, name: '2枚下ろし' },
    { id: 4, name: '3枚下ろし' },
    { id: 5, name: 'お刺身' },
    { id: 6, name: 'ぶつ切り' },
    { id: 7, name: 'その他' }

  ]

  include ActiveHash::Associations
  has_many :items


end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  belongs_to :order
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :fish_fresh
  belongs_to :fish_recipe

  validates :image, :title, :title_text, :fish_fresh_id, :fish_recipe_id, :price, presence: true
  validates :fish_fresh_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :fish_recipe_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 50, less_than_or_equal_to: 999_999 }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :Item


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  belongs_to :order
  
  validates :name, presence: true
  
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    items_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #before_action :authenticate_user!, except: [:index ]

  def index
    @items = Item.all.order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  private
  def item_params
    params.require(:item).permit(:image, :title, :title_text, :fish_fresh_id, :fish_recipe_id, :price ).merge( user_id: current_user.id)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @item = Item.find(params[:item_id])

  end

  def create
    @order = Order.new(order_params)
    if @order.valid?
      @order.save
      redirect_to root_path
    else
      @item = Item.find(params[:item_id])
      render :index, status: :unprocessable_entity
    end
  end



  private

  def order_params
    params.require(:order).permit(:reservation_id, :fish_recipe_id, :telephone).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/items/index.html.erb
<!--メイン-->
<%= render "shared/header" %>
  <div class="fv-container">
    
      <%# 商品一覧 %>
    <div class='item-contents'>
        <h2 class='title'>本日のお魚はこちら</h2>
        <ul class='item-lists'>
            <% @items.each do |i| %>
                <li class='list'>
                    <div class='item-img-content'>
                    <%= image_tag i.image, class: "item-img" %>
                        <div class='item-info'>
                            <h3 class='item-name'>
                            <%= i.title %>
                            </h3>
                            <div class='item-price'>
                            <span><%= i.price %>円<br></span>
                        </div>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
  </div>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/second-header" %>

<div class="items-main">
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

<%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title_text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:fish_fresh_id, FishFresh.all, :id, :name, {}, {class:"select-box", id:"fish-fresh"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:fish_recipe_id, FishRecipe.all, :id, :name, {}, {class:"select-box", id:"fish-recipe"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text">
        <span>販売価格<br>(¥50~999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
    <% end %>
</div>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
    <!-- フッター -->
    <footer class="footer01">
      <div class="footer-container">
        <div class="footer-container-content">
          <div class="footer_logo">万両</div>
          <nav class="footer_nav">
            <ul class="footer_item">
              <li><%= link_to '予約はこちら', "#", class: "list_contact" %></li>
              <li><%= link_to '最新情報', "#", class: "footer_list" %></li>
              <li><%= link_to 'お店情報', "#", class: "footer_list" %></li>
              <li><%= link_to 'お問合せ', "#", class: "footer_list" %></li>
            </ul>
          </nav>
          <ul class="sns-container">
            <li class="list">
              <a href="">ツイッター</a>
            </li>
            <li class="list">
              <a href="">フェイスブック</a>
            </li>
            <li class="list">
              <a href="">インスタグラム</a>
            </li>
          </ul>
          <p class="copylight"><small>© MANRYO</small></p>
        </div>
        <div class="footer-container-image"></div>
      </div>
    </footer>

app/views/shared/_header.html.erb
<!-- ヘッダー -->
    <header class="header01">
      <div class="header_logo">万両</div>
      <nav class="nav">
        <ul class="header_item">
        <% if user_signed_in? %>
          <li><%= link_to '万両の歴史', "#", class: "header_list" %></li>
          <li><%= link_to "#{current_user.name}様", "#", class: "header_list" %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "header_list" %></li>
          <li><%= link_to '予約はこちら', "#", class: "list_contact" %></li>
        <% elsif admin_signed_in? %>
          <li><%= link_to "ログアウト", destroy_admin_session_path, data: { turbo_method: :delete }, class: "header_list" %></li>
          <li><%= link_to '出品はこちら', new_item_path, class: "list_contact" %></li>
        <% else %>
          <li><%= link_to '管理者ログイン', new_admin_session_path, class: "header_list" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "header_list" %></li>
          <li><%= link_to 'ログイン', new_user_session_path, class: "header_list" %></li>
          <% end %>
        </ul>
      </nav>
    </header>

app/views/shared/_second-header.html.erb
    <header class="header01">
      <div class="header_logo">万両</div>
      <nav class="nav">
        <ul class="header_item">
          <li><%= link_to 'トップページに戻る', root_path, class: "header_list" %></li>
        </ul>
      </nav>
    </header>